apiVersion: v1
kind: Service
metadata:
  name: {{ include "observability-app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "observability-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "observability-app.selectorLabels" . | nindent 4 }}
